# Generated by Django 5.0.2 on 2024-02-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enviou_declaracao', models.CharField(max_length=5)),
                ('alteracao_cadastral', models.CharField(max_length=255)),
                ('conjuge', models.CharField(max_length=255)),
                ('dependentes', models.IntegerField()),
                ('conta_banco', models.IntegerField()),
                ('empregado', models.CharField(max_length=255)),
            ],
        ),
    ]
