# Generated by Django 5.0.2 on 2024-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alteracao_cadastral',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='conjuge',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dividas',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='enviou_declaracao',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
