# Generated by Django 5.0.2 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='alteracao_cadastral',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='conjuge',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='empregado',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
